### PR TITLE
Add command line interface

### PR DESCRIPTION
**Pull request by woodcockjosh**
Adds a command line interface
Adds option to only include totals for regression check

### CODE REVIEW

**Comment by gagoar** [comment]
hey @woodcockjosh  I created the CLI for this project. take a look https://www.npmjs.com/package/coverage-diff-cli

hopefully it helps, it also comes with binaries, so you can even run it without needing node.

**Comment by woodcockjosh** [comment]
@gagoar hey that's great. Any chance we could get the same options that are provided by my PR? like `--minimum 0 --decreaseThreshold 0 --criteria branches --criteria statements --totals --output`

**Comment by gagoar** [comment]
yea, if this doesn't require changing the internals of coverage-diff go ahead and create a PR on my implementation!

**Comment by flaviusone** [comment]
Sorry for missing this notification in 2020 😄 . 

Will close this in favor of https://www.npmjs.com/package/coverage-diff-cli. Hats off!

**Pull request closed without merging**
